#include<stdio.h>
#include<conio.h>
    main()
{
    clrscr();
    printf("\t*\t*\t*\t*\t*\t*\t8\n\n\n");
    printf("*\t*\t*\t*\t*\t*\t*\t*\t*\n\n");
    printf("*\t\t*\t\t\t\t\t*\n\n");
    printf("*\t\t*\t\t*\t*\t*\t*\t*\n\n");
    printf("*\t\t*\t\t*\t\t*\t*\n\n");
    printf("*\t*\t*\t*\t*\t*\t*\t*\n\n");
    getch();
}